### ISSUE TITLE
fails on hccap with multiple handshakes

### ISSUE THREAD

**Issue by wheatgrass** [philsmd/hccap2cap#1]
When running hccap2cap against a hccap containing multiple handshakes it gives the message: "[-] .hccap file seems to be _not_ valid", and creates a 0 byte file. It seems to work fine for hccaps containing only one handshake.

**Comment by philsmd** [comment]
Thanks for the suggestion and sorry for the long delay.
The multi-hccap support was added with this patch: https://github.com/philsmd/hccap2cap/commit/6c688d5e273e86a3a8eb4d1719270fde12b83790

Thank you for the report and for helping me to make hccap2cap better
