### ISSUE TITLE
[Feature request] Add support to hccapx v4

### ISSUE THREAD

**Issue by JuniorJPDJ** [philsmd/hccap2cap#2]
Hi,
Can you add support to hccapx v4?

**Comment by philsmd** [comment]
This project is about hccap files only.

Please try to use https://github.com/philsmd/hccapx2cap/ instead ?

**Comment by JuniorJPDJ** [comment]
Oh, sorry.. I missed it..
Found this one in google while searching hccapx to cap
BTW. Thanks for that great programs ;)
